### ISSUE TITLE
React example does not work

### ISSUE THREAD

**Issue by andrew-goldie** [denoland/examples#18]
Following first part of React example using deno version 1.32.5 on MacOS Ventura 13.3.1.

```
deno run --allow-env --allow-read --allow-write npm:create-vite-extra
````

Selected `deno-react` template and `TypeScript` variant.

cd into newly scaffolded project and run

```
deno task dev
```

The following error is displayed:

```
Task dev deno run -A --node-modules-dir npm:vite
error: Uncaught Error: EPERM: operation not permitted, readdir
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:182:12)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1826:16)
    at ext:deno_node/_fs/_fs_readdir.ts:35:22
    at eventLoopTick (ext:core/01_core.js:165:11)
```

**Comment by r3alfar** [comment]
got the same issue on windows 11

```
Task dev deno run -A --node-modules-dir npm:vite
error: Uncaught Error: EINVAL: invalid argument, stat
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:182:12)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1826:16)     
    at ext:deno_node/_fs/_fs_stat.ts:83:97
    at eventLoopTick (ext:core/01_core.js:165:11)
```

**Comment by timgoeller** [comment]
Got the same issue as @r3alfar, also on Windows 11

**Comment by RileySeaburg** [comment]
Same issue on windows 11. 

I have to say the error isn't too helpful either.

As you can tell, the error is coming from the source of the recent node-deno configuration.

```error
Task dev deno run -A --unstable --node-modules-dir npm:vite
error: Uncaught Error: EINVAL: invalid argument, stat
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:182:12)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1826:16)
    at ext:deno_node/_fs/_fs_stat.ts:83:97
    at eventLoopTick (ext:core/01_core.js:181:11)
```
